import {createAUDConsts, createSubFeedConsts} from './actionTypesCreators';
import {
  STREAM, USER, PLAYLIST, SONG, COMMENT,
  LATEST, POPULAR, LONGEST,
  LATEST_SEARCH, POPULAR_SEARCH, LONGEST_SEARCH, YOUTUBE, SOUNDCLOUD
} from './creatorsArgs';

export const {ADD_USERS, UPDATE_USERS, DELETE_USERS} = createAUDConsts(USER);
export const {ADD_STREAMS, UPDATE_STREAMS, DELETE_STREAMS} = createAUDConsts(STREAM);
export const {ADD_PLAYLISTS, UPDATE_PLAYLISTS, DELETE_PLAYLISTS} = createAUDConsts(PLAYLIST);
export const {ADD_SONGS, UPDATE_SONGS, DELETE_SONGS} = createAUDConsts(SONG);
export const {ADD_COMMENTS, UPDATE_COMMENTS, DELETE_COMMENTS} = createAUDConsts(COMMENT);

export const {SET_LATEST, ADD_TO_LATEST, REMOVE_FROM_LATEST} = createSubFeedConsts(LATEST);
export const {SET_POPULAR, ADD_TO_POPULAR, REMOVE_FROM_POPULAR} = createSubFeedConsts(POPULAR);
export const {SET_LONGEST, ADD_TO_LONGEST, REMOVE_FROM_LONGEST} = createSubFeedConsts(LONGEST);

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const {SET_LATEST_SEARCH, ADD_TO_LATEST_SEARCH, REMOVE_FROM_LATEST_SEARCH} = createSubFeedConsts(LATEST_SEARCH);
export const {SET_POPULAR_SEARCH, ADD_TO_POPULAR_SEARCH, REMOVE_FROM_POPULAR_SEARCH} = createSubFeedConsts(POPULAR_SEARCH);
export const {SET_LONGEST_SEARCH, ADD_TO_LONGEST_SEARCH, REMOVE_FROM_LONGEST_SEARCH} = createSubFeedConsts(LONGEST_SEARCH);
export const {SET_YOUTUBE, ADD_TO_YOUTUBE, REMOVE_FROM_YOUTUBE} = createSubFeedConsts(YOUTUBE);
export const {SET_SOUNDCLOUD, ADD_TO_SOUNDCLOUD, REMOVE_FROM_SOUNDCLOUD} = createSubFeedConsts(SOUNDCLOUD);

export const ADD_TO_QUEUE = 'ADD_TO_QUEUE';
export const ADD_TO_QUEUE_TOP = 'ADD_TO_QUEUE_TOP';
export const REMOVE_FROM_QUEUE = 'REMOVE_FROM_QUEUE';

export const PLAY = 'PLAY';
export const PAUSE = 'PAUSE';
export const CLEAR_PLAYER = 'CLEAR_PLAYER';
export const SET_CURRENT_SONG = 'SET_CURRENT_SONG';

export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_SESSION = 'SET_SESSION';
export const CLEAR_SESSION = 'CLEAR_SESSION';
